### ISSUE TITLE
ula-process-barcode package does not exist?

### ISSUE THREAD

**Issue by Tommertom** [rabobank-blockchain/universal-ledger-agent#5]
Hi

Running `npm install ula-process-barcode --save` gives error.

`npm ERR! 404 Not Found - GET https://registry.npmjs.org/ula-process-barcode - Not found`

README.md instruction hence fails on my end

Tom

**Comment by TimoGlastra** [comment]
This is a typo in the documentation. You should install `ula-process-eth-barcode` instead of `ula-process-barcode`.

**Comment by Tommertom** [comment]
Works like a charm
Thanks
